[Date]
; Defines the default timezone used by the date functions
; http://www.php.net/manual/en/datetime.configuration.php#ini.date.timezone
date.timezone = "Asia/Tokyo"

[mbstring]
mbstring.internal_enconding = UTF-8
mbstring.language = neutral
